name: Deploy to Now
on: [push]

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install now
        run: npm i now
      - name: Generate data
        run: npm run data
      - name: Deploy on Zeit - Prod
        run: now --prod --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
